project_id = "elrxbgberccgztipwtcw"

[functions.process-account-deletions]
verify_jwt = false

[functions.extract-products-from-pdf]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-customer-notification]
verify_jwt = false

[functions.process-auto-approvals]
verify_jwt = false
